# 1. Create
# 2. Open
# 3. Read/Write
# 4. Close
# Syntx:-
#   open(file name,'mode)
#                    |......x -> Create
#                    |......r -> Read
#                    |......w -> Write //if your have data already in your file so never run 'w' mode becz its delete all data
#                    |......a -> Append 
# Type of File :- 1. Text File 2. Bnary File 3. .csv file 
# f=open("new.txt",'x') 
# f=open('new1.txt','w')
# f=open('new2.txt','r')
# f=open('new3.txt','r')
# print(f.read())

# Method :- open()
#           readable()   
#           writeable()
#           closeable()
# f=open('n1.txt','x')
# f=open('n2.txt','x')
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# print(f.writable())
# f=open('n3.txt','x')
# print(f.name)
# print(f.mode)
# print(f.encoding)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# f=open('n4.txt','x+')
# print(f.name)
# print(f.mode)
# print(f.encoding)
# print(f.readable())
# print(f.writable())
# print(f.closed)
# f.close()
# print(f.closed)
# f=open('n5.txt','w+')
# print('file_name=',f.name)
# print('file_mode=',f.mode)
# print('file_encode=',f.encoding)
# print('file_readable=',f.readable())
# print('file_writeable=',f.writable())
# print('file_close=',f.closed)
# f.close()
# print('file_close=',f.closed)
# f=open('n5.txt','r+')
# print('file_name=',f.name)
# print('file_mode=',f.mode)
# print('file_encode=',f.encoding)
# print('file_readable=',f.readable())
# print('file_writeable=',f.writable())
# print('file_close=',f.closed)
# f.close()
# print('file_close=',f.closed)
# f=open('n6.txt','a+')
# print('file_name=',f.name)
# print('file_mode=',f.mode)
# print('file_encode=',f.encoding)
# print('file_readable=',f.readable())
# print('file_writeable=',f.writable())
# print('file_close=',f.closed)
# f.close()
# print('file_close=',f.closed)
# Write()-----------------------------------------
# f=open('n7.txt','w')
# f.write("Hello,This is Devanshu \n I am from Sagar \n")
# Data=(' this is python \n Timming is 1:30 \n')
# f.writelines(Data)
# f.writable
# f.close()
# Read()--------------------------------------------
# read() -> read all content
# read(n) -> n is Character
# readlines()
# f=open('n8.txt','a')
# data=('hello im devanshu \n','full stack python \n')
# f.writelines(data)
# print(f.tell())
# print(f.seek())
# f.readable()
# f1=open('n8.txt','r')
# data=f1.read(10)
# data=f1.readable()
# data=f1.readlines()
# data=f1.readline()
# print(data)
# f1.close()
# f.close
# f=open('n9.txt','a+')
# data=("hellow \n","Nishant Ludo")
# f.writelines(data)
# print((f.tell))
# print(f.read())
# f.seek(0)
# print(f.tell)
# print(f.read())
# ________________NEXT_________________________________
# seek(__,__)
#         |___0 -> defualt
#         |___1 ->
#         |___2 ->
# f=open('n10.txt','rb')
# data=("hello \n","im devanshu \n","full stack dev")
# f.writelines(data)
# print(f.tell())
# print(f.read(6))
# print(f.tell())
# print(f.seek(5,1))
# print(f.tell()) 
# print(f.read(10))
# print(f.tell())
# print(f.seek(-6,2))
# print(f.read())
# seek curser ko move krna li leya use krta hai
# tell curser ka current position check krna ki leya use hota ha